name: <<PROJECT_NAME>>

volumes:
  # Volume docker pour la base de données
  data:
    name: ${COMPOSE_PROJECT_NAME}_data

services:
  # Base de données
  database:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: mariadb:latest
    ports: 
      - "3307:3306"
    env_file:
      - ./www/.env
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql
      - ./services/database:/root
    restart: always
  
  # Web
  www:
    container_name: ${COMPOSE_PROJECT_NAME}_www
    depends_on:
      - database
    build: ./services/apache
    ports:
      - "80:80"
      - "443:443"
      - "9001:9000"
    env_file:
      - ./www/.env
    environment:
      - WEB_DOCUMENT_ROOT="/var/www/html/public"
    volumes:
      - ./www:/var/www/html
      - ./services/apache/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    restart: always